name: Docker Image CI

on:
  push:
  branches: [ "master" ]
  

jobs:

  build:
    name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
    uses: docker/login-action@v3.2.0
    with:
      # Username used to log against the Docker registry
      username: kitti57
      # Password or personal access token used to log against the Docker registry
      password: ${{ secrets.DOCKER_PASSWD}}
      # Specifies whether the given registry is ECR (auto, true or false)
      ecr: false 
      # Log out from the Docker registry at the end of a job
      logout: true
          

runs-on: ubuntu-latest
  
steps:
     
    uses: actions/checkout@v4
    name: Docker Image CI

on:
  push:
  branches: [ "master" ]
  

jobs:

  build:
    name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
    uses: docker/login-action@v3.2.0
    with:
      # Username used to log against the Docker registry
    username: kitti57
      # Password or personal access token used to log against the Docker registry
    password: ${{ secrets.DOCKER_PASSWD}}
      # Specifies whether the given registry is ECR (auto, true or false)
    ecr: false 
      # Log out from the Docker registry at the end of a job
    logout: true
          

  runs-on: ubuntu-latest
  
  steps:
     
    -uses: actions/checkout@v4
    -name: Build the Docker image
     
    run: docker build . --file Dockerfile --tag kitti57/NewGitFlow-test
    name: docker push command
    run: docker push  kitti57/NewGitFlow-test
